server:
  port: 8085
  servlet:
    context-path: /cloud
spring:
  config:
    import: config/aliyun.yml

  datasource:
    url: jdbc:mysql://localhost:3306/toptoy
    username: root
    password: wang100086
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false